#C64Studio.MetaData.BASIC:2049,BASIC V2
0 PRINT CHR$(147)
1 PRINT "SO YOU WANT TO COMPLETE THIS TOUGH"
2 PRINT "COOKIE BUT CAN'T BE BOTHERED TO"
3 PRINT "TYPE IN A LISTING FOR INFINITIVE LIVES?"
4 PRINT
5 PRINT "WHY NOT USE THE EASY TO ENTER"
6 PRINT "CHEAT..."
7 PRINT 
8 PRINT "SIMPLY ENTER CHEETAH INSTEAD OF"
9 PRINT "YOUR NAME WHEN YOU GET A HIGH"
10 PRINT "SCORE, AND UNLIMITED LIVES ARE YOURS"
11 PRINT "TO PLAY WITH WHEN YOU NEXT START"
12 PRINT "THE GAME."
